<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr">

<head>
  	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<script src="js/openlayers.js"></script>
	<script src="js/geojson.js"></script>
	<script src="js/jquery-2.1.1.min.js"></script>

  	<link rel="stylesheet" type="text/css" media="screen,projection,print" href="http://thematicmapping.org/css/global.css" />
  	<link rel="stylesheet" type="text/css" media="screen,projection,print" href="http://thematicmapping.org/css/layout2_setup.css" />
  	<link rel="stylesheet" type="text/css" media="screen,projection,print" href="http://thematicmapping.org/css/layout2_text.css" />
  	<link rel="stylesheet" type="text/css" media="screen,projection,print" href="http://thematicmapping.org/css/thematicmapping_old.css" />
  	<title>Représentation Multi-Variable (GeoJSON)</title>
</head>


<body onload="init()" style='margin:10px;'>
	<div id='combos'>
		<div id='var' style='margin:0 0 10px 0;'>Variable à représenter : <select id='selVar'>
			<option value='-1'>Choisir une variable à représenter...</option>
			<option value='1011'>Climate change - Carbon to the Atm. From Land-Use Change - Ann. Net Flux</option>
			<option value='2329'>Climate change - CO2 emissions - per Capita (WDI)</option>
			<option value='2001'>Climate change - Emissions of CH4 - (National Reports, UNFCCC), Excluding Land Use, Land-Use Change and Forestry</option>
			<option value='2004'>Climate change - Emissions of CH4 - (National Reports, UNFCCC), Including Land Use, Land-Use Change and Forestry</option>
			<option value='2303'>Climate change - Emissions of CH4 - from Coal Mining and Solid Fuel Transformation (Model Estimations, EDGAR v.4.2 FT2010)</option>
			<option value='2305'>Climate change - Emissions of CH4 - from Enteric Fermentation Cattle (Model Estimations, EDGAR v.4.2 FT2010)</option>
			<option value='2304'>Climate change - Emissions of CH4 - from Oil and Gas production (Model Estimations, EDGAR v.4.2 FT2010)</option>
			<option value='2308'>Climate change - Emissions of CH4 - from Rice Cultivation (Model Estimations, EDGAR v.4.2 FT2010)</option>
			<option value='2307'>Climate change - Emissions of CH4 - Total (Model Estimations, EDGAR v.4.2 FT2010)</option>
			<option value='1162'>Climate change - Emissions of CH4 - Total (Model Estimations, EDGAR v.4.2)</option>
			<option value='2306'>Climate change - Emissions of CH4 - Waste (Model Estimations, EDGAR v.4.2 FT2010)</option>
			<option value='1998'>Climate change - Emissions of CO2 - (National Reports, UNFCCC), Excluding Land Use, Land-Use Change and Forestry</option>
			<option value='1995'>Climate change - Emissions of CO2 - (National Reports, UNFCCC), Including Land Use, Land-Use Change and Forestry</option>
			<option value='2311'>Climate change - Emissions of CO2 - from  Nonmetallic Minerals Production (Model Estimations, EDGAR v.4.2 FT2010)</option>
			<option value='465'>Climate change - Emissions of CO2 - from Cement Production (CDIAC)</option>
			<option value='2310'>Climate change - Emissions of CO2 - from Forest Fires Decay (Model Estimations, EDGAR v.4.2 FT2010)</option>
			<option value='480'>Climate change - Emissions of CO2 - from Fossil Fuels - Total (CDIAC)</option>
			<option value='469'>Climate change - Emissions of CO2 - from Gas Flaring (CDIAC)</option>
			<option value='470'>Climate change - Emissions of CO2 - from Gas Fuels Consumption (CDIAC)</option>
			<option value='2312'>Climate change - Emissions of CO2 - from Heating/Cooling/Electrical Equipment of Buildings (Model Estimations, EDGAR v.4.2 FT2010)</option>
			<option value='2314'>Climate change - Emissions of CO2 - from Industrial Combustion for Manufacturing (Model Estimations, EDGAR v.4.2 FT2010)</option>
			<option value='473'>Climate change - Emissions of CO2 - from Liquid Fuels Consumption (CDIAC)</option>
			<option value='1150'>Climate change - Emissions of CO2 - from Manufacturing Industries and Construction (IEA)</option>
			<option value='2315'>Climate change - Emissions of CO2 - from Power Plants (Model Estimations, EDGAR v.4.2 FT2010)</option>
			<option value='1147'>Climate change - Emissions of CO2 - from Public Electricity and Heat Production (IEA)</option>
			<option value='2313'>Climate change - Emissions of CO2 - from Road Transport (Model Estimations, EDGAR v.4.2 FT2010)</option>
			<option value='476'>Climate change - Emissions of CO2 - from Solid Fuels Consumption (CDIAC)</option>
			<option value='1153'>Climate change - Emissions of CO2 - from Transport (IEA)</option>
			<option value='2309'>Climate change - Emissions of CO2 - Total (Model Estimations, EDGAR v.4.2 FT2010)</option>
			<option value='1988'>Climate change - Emissions of GHGs - from Agriculture (National Reports, UNFCCC)</option>
			<option value='1986'>Climate change - Emissions of GHGs - from Industrial Processes (National Reports, UNFCCC)</option>
			<option value='1993'>Climate change - Emissions of GHGs - from Transport (National Reports, UNFCCC)</option>
			<option value='1982'>Climate change - Emissions of GHGs - from Waste (National Reports, UNFCCC)</option>
			<option value='1195'>Climate change - Emissions of GHGs - Total (CO2, CH4, N2O, HFCs, PFCs and SF6) (National Reports, UNFCCC), Excluding Land Use, Land-Use Change and Forestry</option>
			<option value='1198'>Climate change - Emissions of GHGs - Total (CO2, CH4, N2O, HFCs, PFCs and SF6) (National Reports, UNFCCC), Including Land Use, Land-Use Change and Forestry</option>
			<option value='2254'>Climate change - Emissions of HFCs  - all Gases</option>
			<option value='1201'>Climate change - Emissions of HFCs,  PFCs and SF6 - Aggregated (National Reports, UNFCCC)</option>
			<option value='2302'>Climate change - Emissions of N2O - from Agriculture (Model Estimations, EDGAR v.4.2 FT2010)</option>
			<option value='1204'>Climate change - Emissions of N2O - from Agriculture (Model Estimations, EDGAR v.4.2)</option>
			<option value='2300'>Climate change - Emissions of N2O - from Soil Emissions (Model Estimations, EDGAR v.4.2 FT2010)</option>
			<option value='2301'>Climate change - Emissions of N2O - Total (Model Estimations, EDGAR v.4.2 FT2010)</option>
			<option value='1210'>Climate change - Emissions of N2O - Total (Model Estimations, EDGAR v.4.2)</option>
			<option value='1980'>Climate change - Emissions of NO2 (National Reports, UNFCCC), Excluding Land Use, Land-Use Change and Forestry</option>
			<option value='1977'>Climate change - Emissions of NO2 (National Reports, UNFCCC), Including Land Use, Land-Use Change and Forestry</option>
			<option value='2323'>Climate change - Land Area where Elevation is Below 5 meters - Percent of Land Area</option>
			<option value='1012'>Climate change - Precipitation - Cubic Kilometers</option>
			<option value='1015'>Climate change - Precipitation - Millimeters</option>
			<option value='436'>Disasters and conflicts - Disasters of Natural Origin - Affected People</option>
			<option value='438'>Disasters and conflicts - Disasters of Natural Origin - Killed People</option>
			<option value='1627'>Disasters and conflicts - Disasters of Natural Origin - Killed per Million People</option>
			<option value='1624'>Disasters and conflicts - Disasters of Natural Origin - Total Affected  per Million People</option>
			<option value='885'>Disasters and conflicts - Disasters of Natural Origin - Total Affected People</option>
			<option value='1726'>Disasters and conflicts - Disasters of Natural Origin (Excluding: Earthquakes, Insect Infestation, Volcanic Eruptions) - Killed People</option>
			<option value='1723'>Disasters and conflicts - Disasters of Natural Origin (Excluding: Earthquakes, Insect Infestation, Volcanic Eruptions) - Killed per Million People</option>
			<option value='1720'>Disasters and conflicts - Disasters of Natural Origin (Excluding: Earthquakes, Insect Infestation, Volcanic Eruptions) - Total Affected People</option>
			<option value='1717'>Disasters and conflicts - Disasters of Natural Origin (Excluding: Earthquakes, Insect Infestation, Volcanic Eruptions) - Total Affected per Million People</option>
			<option value='879'>Disasters and conflicts - Droughts - Killed People</option>
			<option value='588'>Disasters and conflicts - Extreme Temperatures - Killed People</option>
			<option value='543'>Disasters and conflicts - Floods - Killed People</option>
			<option value='960'>Disasters and conflicts - Forest Fire Extent</option>
			<option value='558'>Disasters and conflicts - Slides - Killed People</option>
			<option value='603'>Disasters and conflicts - Waves/Surges - Killed People</option>
			<option value='573'>Disasters and conflicts - Wild Fires - Killed People</option>
			<option value='498'>Disasters and conflicts - Wind Storms - Killed People</option>
			<option value='1672'>Ecosystem management - Agricultural Area</option>
			<option value='2217'>Ecosystem management - Agricultural Area Certified Organic</option>
			<option value='1628'>Ecosystem management - Animal Species - Threatened</option>
			<option value='771'>Ecosystem management - Arable and Permanent Crops</option>
			<option value='686'>Ecosystem management - Arable Land</option>
			<option value='2199'>Ecosystem management - Carbon Stock in Living Forest Biomass</option>
			<option value='1501'>Ecosystem management - Drylands - Percent of Total Area</option>
			<option value='1498'>Ecosystem management - Drylands - Total Area</option>
			<option value='1897'>Ecosystem management - Ecological Footprint</option>
			<option value='2136'>Ecosystem management - Forest Area</option>
			<option value='930'>Ecosystem management - Forest Average Annual Change</option>
			<option value='1966'>Ecosystem management - Forest Harvest Rate</option>
			<option value='200'>Ecosystem management - Forest Plantation Annual Change</option>
			<option value='199'>Ecosystem management - Forest Plantation Extent</option>
			<option value='2201'>Ecosystem management - Forest Primary Designated Function - Conservation of Biodiversity</option>
			<option value='2200'>Ecosystem management - Forest Primary Designated Function - Production</option>
			<option value='2203'>Ecosystem management - Forest Revenue</option>
			<option value='2202'>Ecosystem management - Forest within Protected Areas</option>
			<option value='201'>Ecosystem management - Forests Certified by FSC- Accredited Certification Bodies</option>
			<option value='2247'>Ecosystem management - Forests Certified by PEFC Chain of Custody - Area</option>
			<option value='2246'>Ecosystem management - Forests Certified by PEFC Chain of Custody - Number of Certifications</option>
			<option value='1965'>Ecosystem management - Growing Stock in Forest</option>
			<option value='1256'>Ecosystem management - Mangroves Forest Extent - Protected Area</option>
			<option value='1253'>Ecosystem management - Mangroves Forest Extent - Total Area</option>
			<option value='2209'>Ecosystem management - Oil Palm Fruit - Area Harvested</option>
			<option value='1748'>Ecosystem management - Other Wooded Land Extent</option>
			<option value='691'>Ecosystem management - Permanent Crops</option>
			<option value='1698'>Ecosystem management - Permanent Meadows and Pastures</option>
			<option value='1632'>Ecosystem management - Plant Species - Threatened</option>
			<option value='1832'>Ecosystem management - Primary Forest Annual Change</option>
			<option value='1829'>Ecosystem management - Primary Forest Extent</option>
			<option value='2238'>Ecosystem management - Proportion of Land Area Covered by Forest</option>
			<option value='1876'>Ecosystem management - Protected Areas (Marine, IUCN Categories I-VI and not Classified) - Percent of Marine Area</option>
			<option value='1870'>Ecosystem management - Protected Areas (Marine, IUCN Categories I-VI and not Classified) - Total</option>
			<option value='1871'>Ecosystem management - Protected Areas (Terrestrial and Marine Combined, IUCN Categories I-VI and not Classified) - Percent of Total Territorial Area</option>
			<option value='1712'>Ecosystem management - Protected Areas (Terrestrial and Marine Combined, IUCN Categories I-VI and not Classified) - Total</option>
			<option value='2175'>Ecosystem management - Protected Areas (Terrestrial, IUCN Categories I-VI and not Classified) - Percent of Terrestrial Area</option>
			<option value='2174'>Ecosystem management - Protected Areas (Terrestrial, IUCN Categories I-VI and not Classified) - Total</option>
			<option value='2210'>Ecosystem management - Rapeseed (Colza) - Area Harvested</option>
			<option value='2211'>Ecosystem management - Soybeans - Area Harvested</option>
			<option value='2212'>Ecosystem management - Sugar Beet - Area Harvested</option>
			<option value='2213'>Ecosystem management - Sugar Cane - Area Harvested</option>
			<option value='2214'>Ecosystem management - Sunflower Seed - Area Harvested</option>
			<option value='929'>Ecosystem management - Total Forest Extent</option>
			<option value='194'>Ecosystem management - Wetlands of International Importance (Ramsar Sites) - Area</option>
			<option value='195'>Ecosystem management - Wetlands of International Importance (Ramsar Sites) - Number</option>
			<option value='38'>Ecosystem management - World Heritage Sites - Number</option>
			<option value='3006'>Environmental governance - Aid Donors:  Rio Conventions Objectives - Biodiversity</option>
			<option value='3009'>Environmental governance - Aid Donors:  Rio Conventions Objectives - Climate Change Adaptation</option>
			<option value='3008'>Environmental governance - Aid Donors:  Rio Conventions Objectives - Climate Change Mitigation</option>
			<option value='3007'>Environmental governance - Aid Donors:  Rio Conventions Objectives - Desertification</option>
			<option value='3003'>Environmental governance - Aid Recipients:  Rio Conventions Objectives - Biodiversity</option>
			<option value='3004'>Environmental governance - Aid Recipients:  Rio Conventions Objectives - Climate Change Mitigation</option>
			<option value='3005'>Environmental governance - Aid Recipients:  Rio Conventions Objectives - Desertification</option>
			<option value='279'>Environmental governance - Claimed Exclusive Economic Zone (EEZ)</option>
			<option value='1894'>Environmental governance - Gender-related Development Index (GDI)</option>
			<option value='1895'>Environmental governance - Gender Empowerment Measure (GEM)</option>
			<option value='1904'>Environmental governance - Gini Index</option>
			<option value='1510'>Environmental governance - Human Development Index (HDI)</option>
			<option value='1896'>Environmental governance - Human Poverty Index for Developing Countries (HPI-1)</option>
			<option value='3020'>Environmental governance - Improved Drinking Water Coverage - Percentage of Rural Population</option>
			<option value='3021'>Environmental governance - Improved Drinking Water Coverage - Percentage of Total Population</option>
			<option value='3022'>Environmental governance - Improved Drinking Water Coverage - Percentage of Urban Population</option>
			<option value='48'>Environmental governance - Improved Drinking Water Coverage - Rural Population</option>
			<option value='1034'>Environmental governance - Improved Drinking Water Coverage - Total Population</option>
			<option value='32'>Environmental governance - Improved Drinking Water Coverage - Urban Population</option>
			<option value='3023'>Environmental governance - Improved Sanitation Coverage - Percentage of Rural Population</option>
			<option value='2260'>Environmental governance - Improved Sanitation Coverage - Percentage of Total Population</option>
			<option value='3024'>Environmental governance - Improved Sanitation Coverage - Percentage of Urban Population</option>
			<option value='28'>Environmental governance - Improved Sanitation Coverage - Rural Population</option>
			<option value='1029'>Environmental governance - Improved Sanitation Coverage - Total Population</option>
			<option value='52'>Environmental governance - Improved Sanitation Coverage - Urban Population</option>
			<option value='1777'>Environmental governance - ISO 14001 Certifications</option>
			<option value='2250'>Environmental governance - Net Official Aid Received</option>
			<option value='224'>Environmental governance - Official Development Assistance and Official Aid</option>
			<option value='1477'>Environmental governance - Participation in Treaties - Basel Convention</option>
			<option value='1488'>Environmental governance - Participation in Treaties - Convention on Biological Diversity</option>
			<option value='1578'>Environmental governance - Participation in Treaties - Convention on International Trade in Endangered Species of Wild Fauna and Flora</option>
			<option value='1577'>Environmental governance - Participation in Treaties - Convention on the Conservation of Migratory Species of Wild Animals</option>
			<option value='1478'>Environmental governance - Participation in Treaties - Kyoto Protocol</option>
			<option value='1575'>Environmental governance - Participation in Treaties - Ramsar Convention on Wetlands</option>
			<option value='1580'>Environmental governance - Participation in Treaties - Rotterdam Convention</option>
			<option value='1573'>Environmental governance - Participation in Treaties - Stockholm Convention on Persistent Organic Pollutants</option>
			<option value='1579'>Environmental governance - Participation in Treaties - United Nations Convention on the Law of the Sea</option>
			<option value='1574'>Environmental governance - Participation in Treaties - United Nations Convention to Combat Desertification</option>
			<option value='1479'>Environmental governance - Participation in Treaties - United Nations Framework Convention on Climate Change</option>
			<option value='1487'>Environmental governance - Participation in Treaties - Vienna Convention and Montreal Protocol</option>
			<option value='1576'>Environmental governance - Participation in Treaties - World Heritage Convention</option>
			<option value='1850'>Environmental governance - Percentage of Population Below US $ 1.25 per Day Consumption</option>
			<option value='1854'>Environmental governance - Percentage of Population Below US $ 2 per Day Consumption</option>
			<option value='1857'>Environmental governance - Poverty Gap at US $ 1.25 (PPP)</option>
			<option value='1858'>Environmental governance - Poverty Gap at US $ 2 (PPP)</option>
			<option value='1900'>Environmental governance - Proportion of Households with Access to Secure Tenure</option>
			<option value='1923'>Environmental governance - Refugee Population by Country of Asylum</option>
			<option value='1925'>Environmental governance - Refugee Population by Country of Origin</option>
			<option value='949'>General - Alternative Conversion Factor (Exchange Rate)</option>
			<option value='1812'>General - Births</option>
			<option value='2316'>General - Cash Surplus/Deficit - Percent of of GDP</option>
			<option value='100'>General - Central Government Debt - Percent of GDP</option>
			<option value='2327'>General - Charges for the Use of Intellectual Property - Payments</option>
			<option value='2345'>General - Charges for the Use of Intellectual Property - Receipts</option>
			<option value='1776'>General - Children Under 5 with Diarrhoea - Percent</option>
			<option value='1903'>General - Consumer Price Index (2000  = 100)</option>
			<option value='1085'>General - Continental Shelf Area</option>
			<option value='2135'>General - Country Area</option>
			<option value='613'>General - Crude Birth Rate</option>
			<option value='247'>General - Crude Death Rate</option>
			<option value='1480'>General - Economically Active Population</option>
			<option value='2173'>General - Emissions of CO2 per GDP (PPP)</option>
			<option value='614'>General - Exports of Goods and Services</option>
			<option value='2322'>General - External Debt Stocks - Total</option>
			<option value='49'>General - Fertility</option>
			<option value='843'>General - Foreign Direct Investment - Net Inflows</option>
			<option value='227'>General - General Government Final Consumption Expenditure</option>
			<option value='1909'>General - Girls to Boys Ratio in Primary Education Enrolment</option>
			<option value='753'>General - Gross Domestic Product</option>
			<option value='756'>General - Gross Domestic Product - Annual Percentage Growth Rate</option>
			<option value='758'>General - Gross Domestic Product - Purchasing Power Parity</option>
			<option value='1121'>General - Gross Enrolment Ratio in Primary Education</option>
			<option value='1124'>General - Gross Enrolment Ratio in Secondary Education</option>
			<option value='1133'>General - Gross Enrolment Ratio in Tertiary Education (ISCED Categories 5 and 6)</option>
			<option value='1887'>General - Gross National Income</option>
			<option value='1474'>General - Healthy Life Expectancy (HALE)</option>
			<option value='633'>General - Household Final Consumption Expenditure - Total</option>
			<option value='619'>General - Imports of Goods and Services</option>
			<option value='335'>General - Industry Value Added</option>
			<option value='776'>General - Infant Mortality Rate</option>
			<option value='1138'>General - International Tourism - Arrivals</option>
			<option value='1141'>General - International Tourism - Departures</option>
			<option value='1685'>General - Land Area</option>
			<option value='1088'>General - Length of Coastline</option>
			<option value='237'>General - Life Expectancy</option>
			<option value='976'>General - Manufacturing Value Added</option>
			<option value='1905'>General - Maternal Mortality Ratio</option>
			<option value='231'>General - Military Expenditures - Percent of GDP</option>
			<option value='986'>General - Mobile Cellular Subscriptions per 100 Inhabitants</option>
			<option value='1662'>General - Motor Vehicles in Use - Commercial Vehicles per Thousand People</option>
			<option value='1656'>General - Motor Vehicles in Use - Number of Commercial Vehicles</option>
			<option value='1653'>General - Motor Vehicles in Use - Number of Passenger Cars</option>
			<option value='1659'>General - Motor Vehicles in Use - Passenger Cars per Thousand People</option>
			<option value='1127'>General - Net Enrolment Ratios in Primary Education</option>
			<option value='1130'>General - Net Enrolment Ratios in Secondary Education</option>
			<option value='2324'>General - Net Migration</option>
			<option value='1422'>General - Net Migration Rate</option>
			<option value='1418'>General - Net Number of Migrants</option>
			<option value='2325'>General - Net ODA Received - per Capita</option>
			<option value='1425'>General - Net Reproduction Rate</option>
			<option value='3014'>General - Number of people undernourished</option>
			<option value='2326'>General - Patent Applications - non Residents</option>
			<option value='2317'>General - Patent Applications - Residents</option>
			<option value='989'>General - Personal Computers per 100 People</option>
			<option value='2111'>General - Population - Aged 0 - 14</option>
			<option value='2106'>General - Population - Aged 0 - 4</option>
			<option value='2105'>General - Population - Aged 15 - 64</option>
			<option value='1428'>General - Population - Aged 65 and Over</option>
			<option value='1434'>General - Population - Median Age</option>
			<option value='1806'>General - Population - Projection</option>
			<option value='2112'>General - Population - Sex Ratio</option>
			<option value='1810'>General - Population - Total both Sexes</option>
			<option value='9'>General - Population - Total Female</option>
			<option value='699'>General - Population - Total Male</option>
			<option value='294'>General - Population Density</option>
			<option value='696'>General - Population Growth Rate</option>
			<option value='1507'>General - Population in Drylands - Percent of Total Population</option>
			<option value='1504'>General - Population in Drylands - Total</option>
			<option value='280'>General - Population Within 100 Kilometers of Coast</option>
			<option value='1801'>General - Railways Traffic - Goods Hauled</option>
			<option value='1511'>General - Railways Traffic - Passenger Carried</option>
			<option value='1912'>General - Ratio of Literate Women to Men Aged 15-24</option>
			<option value='2259'>General - Reported Cholera Cases - Number of Cases</option>
			<option value='1883'>General - Reported Cholera Cases - Number of Deaths</option>
			<option value='1772'>General - Reported Malaria Cases - Total Number</option>
			<option value='1775'>General - Reported Malaria Cases - Total Number per 100,000 Population</option>
			<option value='2328'>General - Research and Development Expenditure - percent of GDP</option>
			<option value='2248'>General - Road Density</option>
			<option value='1802'>General - Road Traffic - Goods Hauled per Km</option>
			<option value='1803'>General - Roads - Total Network</option>
			<option value='2180'>General - Rural Population - Total</option>
			<option value='1665'>General - Rural Population - Total (Projection)</option>
			<option value='2155'>General - School Age Population - Primary</option>
			<option value='2156'>General - School Age Population - Secondary</option>
			<option value='2157'>General - School Age Population - Tertiary</option>
			<option value='333'>General - Services Value Added - Percent of GDP</option>
			<option value='2151'>General - Teaching Staff in Primary Education</option>
			<option value='2152'>General - Teaching Staff in Secondary Education</option>
			<option value='2153'>General - Teaching Staff in Tertiary Education</option>
			<option value='1464'>General - Telephone Main Lines in Use</option>
			<option value='1461'>General - Telephone Main Lines in Use per 100 People</option>
			<option value='1471'>General - Television Sets</option>
			<option value='1468'>General - Television Sets per 1000 People</option>
			<option value='277'>General - Territorial Sea</option>
			<option value='2164'>General - Total Health Expenditure  - Percent of GDP</option>
			<option value='2154'>General - Total Number of Graduates in Tertiary Education</option>
			<option value='1974'>General - Total Surface Area</option>
			<option value='1483'>General - Total Unemployment - Percent of Total Labor Force</option>
			<option value='620'>General - Trade - Percent of GDP</option>
			<option value='773'>General - Under-Five Mortality Rate</option>
			<option value='826'>General - Urban Population - Average Annual Growth Rate (Projection)</option>
			<option value='340'>General - Urban Population - Percent of Total Population</option>
			<option value='828'>General - Urban Population - Percent of Total Population (Projection)</option>
			<option value='341'>General - Urban Population - Total</option>
			<option value='832'>General - Urban Population - Total (Projection)</option>
			<option value='1930'>Harmful substances and hazardous waste - Concentrations of Particulate Matter less than 10 microns (PM10)</option>
			<option value='2169'>Harmful substances and hazardous waste - Consumption of Ozone-Depleting Substances - All</option>
			<option value='2171'>Harmful substances and hazardous waste - Consumption of Ozone-Depleting Substances - Carbon Tetrachloride</option>
			<option value='1571'>Harmful substances and hazardous waste - Consumption of Ozone-Depleting Substances - Chlorofluorocarbons (CFCs)</option>
			<option value='2170'>Harmful substances and hazardous waste - Consumption of Ozone-Depleting Substances - Halons</option>
			<option value='1708'>Harmful substances and hazardous waste - Consumption of Ozone-Depleting Substances - Hydrochlorofluorocarbons (HCFCs)</option>
			<option value='1706'>Harmful substances and hazardous waste - Consumption of Ozone-Depleting Substances - Methyl Bromide</option>
			<option value='2172'>Harmful substances and hazardous waste - Consumption of Ozone-Depleting Substances - Methyl Chloroform</option>
			<option value='418'>Harmful substances and hazardous waste - Diseases of the Respiratory System - Number of Deaths</option>
			<option value='1761'>Harmful substances and hazardous waste - Diseases of the Respiratory System - Number of Deaths per 100,000 Population</option>
			<option value='1835'>Harmful substances and hazardous waste - Emissions of CO - Total (National Reports, UNFCCC)</option>
			<option value='1216'>Harmful substances and hazardous waste - Emissions of NMVOC - Total (Model Estimations, EDGAR v.4.2)</option>
			<option value='1843'>Harmful substances and hazardous waste - Emissions of NMVOC - Total (National Reports, UNFCCC)</option>
			<option value='1219'>Harmful substances and hazardous waste - Emissions of NOx - Total (Model Estimations, EDGAR v.4.2)</option>
			<option value='1846'>Harmful substances and hazardous waste - Emissions of NOX - Total (National Reports, UNFCCC)</option>
			<option value='1459'>Harmful substances and hazardous waste - Emissions of Organic Water Pollutants (BOD) - per Worker</option>
			<option value='1458'>Harmful substances and hazardous waste - Emissions of Organic Water Pollutants (BOD) - Total</option>
			<option value='1890'>Harmful substances and hazardous waste - Emissions of Particulates Smaller than 2.5 Microns</option>
			<option value='1222'>Harmful substances and hazardous waste - Emissions of SO2 - Total (Model Estimations, EDGAR v.4.2)</option>
			<option value='1840'>Harmful substances and hazardous waste - Emissions of SO2 - Total (National Reports, UNFCCC)</option>
			<option value='2215'>Harmful substances and hazardous waste - Hazardous Pesticides - Exports</option>
			<option value='2216'>Harmful substances and hazardous waste - Hazardous Pesticides - Imports</option>
			<option value='1540'>Harmful substances and hazardous waste - Hazardous Waste - Production</option>
			<option value='2160'>Harmful substances and hazardous waste - Hospital Beds - per 10 000 Population</option>
			<option value='2021'>Harmful substances and hazardous waste - Nitrogen (N Total Nutrients) - Consumption</option>
			<option value='2018'>Harmful substances and hazardous waste - Nitrogen (N Total Nutrients) - Production</option>
			<option value='1543'>Harmful substances and hazardous waste - Nuclear Waste - Spent Fuel Arisings</option>
			<option value='2158'>Harmful substances and hazardous waste - Number of Physicians</option>
			<option value='2159'>Harmful substances and hazardous waste - Nursing and Midwifery Personnel Density - per 10 000 Population</option>
			<option value='1752'>Harmful substances and hazardous waste - Pesticides Consumption - Fungicides, Bactericides</option>
			<option value='1106'>Harmful substances and hazardous waste - Pesticides Consumption - Herbicides</option>
			<option value='1109'>Harmful substances and hazardous waste - Pesticides Consumption - Insecticides</option>
			<option value='1112'>Harmful substances and hazardous waste - Pesticides Consumption - Mineral Oils</option>
			<option value='1115'>Harmful substances and hazardous waste - Pesticides Consumption - Plant Growth Regulators</option>
			<option value='1118'>Harmful substances and hazardous waste - Pesticides Consumption - Rodenticides</option>
			<option value='2015'>Harmful substances and hazardous waste - Phosphate (P2O5 Total Nutrients) - Consumption</option>
			<option value='2012'>Harmful substances and hazardous waste - Phosphate (P2O5 Total Nutrients) - Production</option>
			<option value='1949'>Harmful substances and hazardous waste - Population Affected by Water Related Disease</option>
			<option value='3019'>Harmful substances and hazardous waste - Population Using Solid Fuels</option>
			<option value='2009'>Harmful substances and hazardous waste - Potash (K2O Total Nutrients) - Consumption</option>
			<option value='2006'>Harmful substances and hazardous waste - Potash (K2O Total Nutrients) - Production</option>
			<option value='1703'>Harmful substances and hazardous waste - Total Amount of Generated Hazardous Wastes</option>
			<option value='2098'>Harmful substances and hazardous waste - Total Pesticides - Exports</option>
			<option value='2099'>Harmful substances and hazardous waste - Total Pesticides - Imports</option>
			<option value='1617'>Harmful substances and hazardous waste - Transboundary Movements of Hazardous and Other Wastes - Exports</option>
			<option value='1616'>Harmful substances and hazardous waste - Transboundary Movements of Hazardous and Other Wastes - Imports</option>
			<option value='2134'>Resource efficiency - Agricultural Area Irrigated</option>
			<option value='123'>Resource efficiency - Agricultural Production Index Base 2004-2006 - Total</option>
			<option value='331'>Resource efficiency - Agriculture Value Added - Percent of GDP</option>
			<option value='2165'>Resource efficiency - Air Transport - Passengers Carried</option>
			<option value='1534'>Resource efficiency - Amounts of Municipal Waste - Total</option>
			<option value='2125'>Resource efficiency - Aquaculture Production - Inland Waters</option>
			<option value='1644'>Resource efficiency - Aquaculture Production - Marine</option>
			<option value='932'>Resource efficiency - Aquaculture Production - Total</option>
			<option value='2252'>Resource efficiency - Blue Water Footprint of National Production</option>
			<option value='2128'>Resource efficiency - Cadmium (Cd) Consumption</option>
			<option value='2127'>Resource efficiency - Cadmium (Cd) Production</option>
			<option value='2208'>Resource efficiency - Cereals - Area Harvested</option>
			<option value='1'>Resource efficiency - Cereals - Production</option>
			<option value='839'>Resource efficiency - Cereals - Yield</option>
			<option value='1568'>Resource efficiency - Civil Aviation Traffic - International Freight</option>
			<option value='1556'>Resource efficiency - Civil Aviation Traffic - International Kilometers Flown</option>
			<option value='1562'>Resource efficiency - Civil Aviation Traffic - International Passengers Carried</option>
			<option value='1565'>Resource efficiency - Civil Aviation Traffic - Total Freight</option>
			<option value='1553'>Resource efficiency - Civil Aviation Traffic - Total Kilometers Flown</option>
			<option value='1559'>Resource efficiency - Civil Aviation Traffic - Total Passengers Carried</option>
			<option value='1018'>Resource efficiency - Desalinated Water Produced</option>
			<option value='2181'>Resource efficiency - Electricity - Distribution Losses (IEA)</option>
			<option value='2182'>Resource efficiency - Electricity - Domestic Supply (IEA)</option>
			<option value='2183'>Resource efficiency - Electricity - Nuclear Industry (IEA)</option>
			<option value='2184'>Resource efficiency - Electricity - Production (IEA)</option>
			<option value='2186'>Resource efficiency - Electricity - Total Final Consumption (IEA)</option>
			<option value='2185'>Resource efficiency - Electricity Consumption - Residential (IEA)</option>
			<option value='2187'>Resource efficiency - Electricity Consumption - Transport Sector (IEA)</option>
			<option value='992'>Resource efficiency - Energy Capacity - Nuclear</option>
			<option value='1736'>Resource efficiency - Energy Consumption for Road Transport Sector - Total (IEA)</option>
			<option value='1730'>Resource efficiency - Energy Consumption for Total Transport Sector - Total (IEA)</option>
			<option value='2319'>Resource efficiency - Energy Imports Net  - Percent of Energy Use</option>
			<option value='2320'>Resource efficiency - Energy Production</option>
			<option value='2039'>Resource efficiency - Energy Production - Biodiesel (IEA)</option>
			<option value='2045'>Resource efficiency - Energy Production - Biogasoline (IEA)</option>
			<option value='927'>Resource efficiency - Energy Production - Combustible Renewables and Waste (IEA)</option>
			<option value='1741'>Resource efficiency - Energy Production - Crude Oil (IEA)</option>
			<option value='1967'>Resource efficiency - Energy Production - Hydro (IEA)</option>
			<option value='1744'>Resource efficiency - Energy Production - Natural gas (IEA)</option>
			<option value='1745'>Resource efficiency - Energy Production - Nuclear (IEA)</option>
			<option value='2048'>Resource efficiency - Energy Production - Other Liquid Biofuels (IEA)</option>
			<option value='344'>Resource efficiency - Energy Production - Total (IEA)</option>
			<option value='2321'>Resource efficiency - Energy Use - per Capita</option>
			<option value='1525'>Resource efficiency - Energy use (kg oil equivalent) per $1,000 GDP (Constant 2005 PPP $)</option>
			<option value='278'>Resource efficiency - Exclusive Fishing Zone (EFZ)</option>
			<option value='938'>Resource efficiency - Fish Catch - Inland Waters</option>
			<option value='940'>Resource efficiency - Fish Catch - Marine</option>
			<option value='337'>Resource efficiency - Fish Catch - Total</option>
			<option value='2126'>Resource efficiency - Fishery Production - Inland Waters</option>
			<option value='271'>Resource efficiency - Fishery Production - Marine</option>
			<option value='1970'>Resource efficiency - Fishery Production - Total</option>
			<option value='2330'>Resource efficiency - Food Supply Quantity</option>
			<option value='2206'>Resource efficiency - Food Supply Quantity - Cereals</option>
			<option value='2204'>Resource efficiency - Food Supply Quantity - Fish and Seafood</option>
			<option value='2205'>Resource efficiency - Food Supply Quantity - Meat</option>
			<option value='2251'>Resource efficiency - Green Water Footprint of National Production</option>
			<option value='2253'>Resource efficiency - Grey Water Footprint of National Production</option>
			<option value='261'>Resource efficiency - Groundwater Produced Internally</option>
			<option value='2130'>Resource efficiency - Lead (Pb) Consumption</option>
			<option value='2129'>Resource efficiency - Lead (Pb) Production</option>
			<option value='2207'>Resource efficiency - Livestock Production Index Base 2004-2006 - Total</option>
			<option value='2131'>Resource efficiency - Mercury (Hg) Production</option>
			<option value='2239'>Resource efficiency - Municipal Waste Collection</option>
			<option value='1792'>Resource efficiency - Nuclear Power Reactors Operable in 2005 - Electrical Output</option>
			<option value='1791'>Resource efficiency - Nuclear Power Reactors Operable in 2005 - Number</option>
			<option value='1799'>Resource efficiency - Nuclear Power Reactors Under Construction in 2005 - Electrical Output</option>
			<option value='1797'>Resource efficiency - Nuclear Power Reactors Under Construction in 2005 - Number</option>
			<option value='2137'>Resource efficiency - Permanent Crops Irrigated</option>
			<option value='1546'>Resource efficiency - Population Connected to Public Waste Water Treatement Plants</option>
			<option value='1610'>Resource efficiency - Proportion of Total Renewable Water Resources</option>
			<option value='2166'>Resource efficiency - Railways Lines - Total Route-km</option>
			<option value='1817'>Resource efficiency - Rice - Area Harvested</option>
			<option value='1820'>Resource efficiency - Rice - Production</option>
			<option value='1821'>Resource efficiency - Rice - Yield</option>
			<option value='202'>Resource efficiency - Roundwood - Production</option>
			<option value='1550'>Resource efficiency - Sewage Sludge Production</option>
			<option value='1495'>Resource efficiency - Surface Water Produced Internally</option>
			<option value='1704'>Resource efficiency - Total Amount of Generated Other Wastes</option>
			<option value='2138'>Resource efficiency - Total Area Equipped for Irrigation</option>
			<option value='1942'>Resource efficiency - Total Dam Capacity</option>
			<option value='2036'>Resource efficiency - Total Final Energy Consumption - Biodiesel (IEA)</option>
			<option value='2042'>Resource efficiency - Total Final Energy Consumption - Biogasoline (IEA)</option>
			<option value='2051'>Resource efficiency - Total Final Energy Consumption - Other Liquid Biofuels (IEA)</option>
			<option value='217'>Resource efficiency - Total Final Energy Consumption - Total (IEA)</option>
			<option value='849'>Resource efficiency - Total Primary Energy Supply - Coal and Coal Products (IEA)</option>
			<option value='946'>Resource efficiency - Total Primary Energy Supply - Combustible Renewables and Waste (IEA)</option>
			<option value='851'>Resource efficiency - Total Primary Energy Supply - Crude Oil (IEA)</option>
			<option value='918'>Resource efficiency - Total Primary Energy Supply - Geothermal (IEA)</option>
			<option value='858'>Resource efficiency - Total Primary Energy Supply - Hydro (IEA)</option>
			<option value='861'>Resource efficiency - Total Primary Energy Supply - Natural Gas (IEA)</option>
			<option value='862'>Resource efficiency - Total Primary Energy Supply - Nuclear (IEA)</option>
			<option value='919'>Resource efficiency - Total Primary Energy Supply - Petroleum Products (IEA)</option>
			<option value='923'>Resource efficiency - Total Primary Energy Supply - Solar, Wind, Tide and Other (IEA)</option>
			<option value='767'>Resource efficiency - Total Primary Energy Supply - Total (IEA)</option>
			<option value='2163'>Resource efficiency - Transport Sector Diesel Fuel Consumption per Capita</option>
			<option value='2162'>Resource efficiency - Transport Sector Gasoline Fuel Consumption per Capita</option>
			<option value='1021'>Resource efficiency - Treated Waste Water Reused</option>
			<option value='1552'>Resource efficiency - Waste Recycling Rates - Glass</option>
			<option value='1551'>Resource efficiency - Waste Recycling Rates - Paper and Cardboard</option>
			<option value='2161'>Resource efficiency - Water Footprint</option>
			<option value='3011'>Resource efficiency - Water footprint of consumption of agricultural products</option>
			<option value='3012'>Resource efficiency - Water footprint of consumption of industrial products</option>
			<option value='3013'>Resource efficiency - Water footprint of domestic water consumption</option>
			<option value='1497'>Resource efficiency - Water Resources - Dependency Ratio</option>
			<option value='1947'>Resource efficiency - Water Resources - Overlap Between Surface Water and Groundwater</option>
			<option value='1960'>Resource efficiency - Water Resources - Total Exploitable</option>
			<option value='1492'>Resource efficiency - Water Resources - Total External (Actual)</option>
			<option value='1004'>Resource efficiency - Water Resources - Total Internal Renewable</option>
			<option value='1943'>Resource efficiency - Water Resources - Total Renewable (Actual)</option>
			<option value='269'>Resource efficiency - Water Use - Agricultural Water Withdrawal</option>
			<option value='268'>Resource efficiency - Water Use - Industrial Water Withdrawal</option>
			<option value='267'>Resource efficiency - Water Use - Municipal Water Withdrawal</option>
			<option value='262'>Resource efficiency - Water Use - Total Groundwater Withdrawal</option>
			<option value='1952'>Resource efficiency - Water Use - Total Surface Water Withdrawal</option>
			<option value='1100'>Resource efficiency - Water Use - Total Water Withdrawal</option>
		</select><button style='margin:0 0 0 10px;'>Affichage</button></div>
	</div>
	    <div id="olmap" style='width:100%; height:600px;'></div>
		<div id='infoTxt' style='margin:20px 30px 0 30px; font-size:14px; font-weight:bold;'>
			<div><span>Pays => </span><span id="country"></span></div>
			<div><span>Valeur => </span><span id="valeur"></span></div>
			<div><span>Rang Mondial => </span><span id="rang"></span><span> / </span><span id="rang_total"></span></div>
			<table border='0' style='margin:10px 0 0 0; font-size:12px;'>
				<tr><td>Minimum => </td><td><span id='valMin'></span></td></tr>		
				<tr><td>Maximum => </td><td><span id='valMax'></span></td></tr>		
				<tr><td>Moyenne => </td><td><span id='valMean'></span></td></tr>		
			</table>
		</div>
	</body>
</html>